### ISSUE TITLE
Error in webhook of workflow and task statuses

### ISSUE THREAD

**Issue by JCHacking** [conductor-oss/conductor#131]
**Describe the bug**
When conductor is configured without these 2 properties:
- conductor.status-notifier.notification.headerPrefer
- conductor.status-notifier.notification.headerPreferValue

The request is not a valid http

**Details**
Conductor version: 3.19.0

**To Reproduce**
1. Configure conductor withtou conductor.status-notifier.notification.headerPrefer and conductor.status-notifier.notification.headerPreferValue
2. Create workflow
3. Start workflow
4. See request sended by webhook is http invalid

**Expected behavior**
You should check that they have content before doing 
```java 
headers.put(config.getHeaderPrefer(), config.getHeaderPreferValue());
```

**Comment by SSingh206** [comment]
Thank you
