### ISSUE TITLE
Sub_Workflows are taking very long time to change status from SCHEDULED to IN_PROGRESS state

### ISSUE THREAD

**Issue by GKSubs** [conductor-oss/conductor#225]
**Describe the bug**
We are using Netflix Conductor version 3.14.0, been using one year. Since two weeks we are observing that the Sub_Workflows (that are part of main Workflows) are taking very long time to change status from SCHEDULED to IN_PROGRESS state, time is varying anywhere from 1 minute to 1 hour. There was no issue with native task state changes, issue observed at Sub_Workflow which are containing custom python tasks. Also observed that all of Sub_workflows (from various running Workflows) getting paused at the SCHEDULED state around same time (may be with difference of few seconds), and getting resumed around same time.

**Details**
Conductor version: 3.14.0
Persistence implementation: Postgres
Queue implementation: Not sure, been using default one that comes with Netflix 3.14.0
Lock: Not sure, been using default one that comes with Netflix 3.14.0
Workflow definition: Every workflow that we have
Task definition: Custom
Event handler definition: Custom

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by verkala** [comment]
Restart NFC with Blank PostgreSQL (persistent layer).

**Comment by GKSubs** [comment]
Worked, thanks.
