### ISSUE TITLE
[Java Client v4] Add back lease extension to Worker

### ISSUE THREAD

**Issue by jmigueprieto** [conductor-oss/conductor#306]
**Acceptance Criteria**
- Java Client v4 should support lease extension as Client v3

**Comment by lbestatlas** [comment]
@jmigueprieto I have also noticed that the Worker method getBatchPollTimeoutInMS has been left out, this is what allows tasks to individually set the batch poll timeout. Can you please add it back in also.

**Comment by jmigueprieto** [comment]
@lbestatlas we'll make sure to add it back. Thank you.
