### ISSUE TITLE
AWS SDK not able to assume IAM role for service accounts in Kubernetes

### ISSUE THREAD

**Issue by dcopestake** [conductor-oss/conductor#33]
**Describe the bug**
The Conductor components which make use of the AWS SDK (i.e. `conductor-awssqs-event-queue` etc.) will currently _not_ assume an IAM role which is associated with a Kubernetes service account. Enabling the AWS SDK debug logs reveals that the [WebIdentityTokenCredentialsProvider](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/WebIdentityTokenCredentialsProvider.html) credentials provider is _not_ being included as part of the [DefaultAWSCredentialsProviderChain](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html):

```
c.a.a.AWSCredentialsProviderChain : Unable to load credentials from EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY))
c.a.a.AWSCredentialsProviderChain : Unable to load credentials from SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey)
c.a.a.AWSCredentialsProviderChain : Unable to load credentials from com.amazonaws.auth.profile.ProfileCredentialsProvider@109f8c7e: profile file cannot be null
c.a.a.AWSCredentialsProviderChain : Loading credentials from com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@75156240
```

**Details**
Conductor version: Snapshot (main at fec3116)
Persistence implementation: Postgres
Queue implementation: Postgres, Dynoqueues, SQS

**To Reproduce**
Steps to reproduce the behaviour:
1. Build server component from main at fec3116 using the Dockerfile from `docker/server`
2. Run the server using Docker image as a service in Kubernetes with the pods using a [service account with an IAM role associated](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html)

**Expected behavior**
The WebIdentityTokenCredentialsProvider should be used to assume the IAM role and these credentials should be used for all AWS SDK requests.

**Additional context**
In our AWS EKS cluster we use [IAM roles for service accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) which means making use of the [WebIdentityTokenCredentialsProvider](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/WebIdentityTokenCredentialsProvider.html) credentials provider. It turns out that the current version of the AWS SDK used by Conductor is 1.11.86, however the [minimum supported version to support the WebIdentityTokenCredentialsProvider provider is 1.11.704](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html). I've upgraded [our fork to use the latest 1.11 version](https://github.com/conductor-oss/conductor/commit/0f012700ece5e8b87e02f47e9639cd8400971eb7) (which is currently 1.11.1034) and this seems to resolve the issue. It's worth noting that as part of this change you _also_ need to make sure that `com.amazonaws:aws-java-sdk-sts` is included in the class path at runtime.

**Comment by denniscodes** [comment]
As of 3.17.0 the AWS SDK has been updated:
revAwsSdk = '1.12.635'.

Does this help?
