### ISSUE TITLE
use the conductoross/conductor:3.15.0  issue some problems

### ISSUE THREAD

**Issue by antz-H** [conductor-oss/conductor#65]
**Describe the bug**
I want to use the image(conductoross/conductor:3.15.0) in local to try conductor . But when I use the  conductor.db.type=redis_standalone   and run it , some error message appeared.

**Details**
Conductor version:   docker-image: conductoross/conductor:3.15.0
Persistence implementation: Redis , es
Queue implementation:  Redis
Lock: Redis 

this is the configuration
```
# Database persistence type.
# Below are the properties for redis
conductor.db.type=redis_standalone
conductor.queue.type=redis_standalone

conductor.redis.hosts=10.200.0.69:6379
conductor.redis-lock.serverAddress=redis://10.200.0.69:6379
conductor.redis.taskDefCacheRefreshInterval=1
conductor.redis.workflowNamespacePrefix=conductor
conductor.redis.queueNamespacePrefix=conductor_queues

# Elastic search instance indexing is enabled.
conductor.indexing.enabled=true
conductor.elasticsearch.url=http://10.200.0.69:9200
conductor.elasticsearch.indexName=conductor
conductor.elasticsearch.version=7
conductor.elasticsearch.clusterHealthColor=yellow

# Additional modules for metrics collection exposed to Prometheus (optional)
conductor.metrics-prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus

# Load sample kitchen sink workflow
loadSample=true
```

this is the run command
```
docker run -v /home/config-redis.properties:/app/config/config.properties --init -p 8080:8080 -p 1234:5000   conductoross/conductor:3.15.0

```

this is error message.
![image](https://github.com/conductor-oss/conductor/assets/43114886/d3f4aab4-fa71-4816-a7dc-e27180c7bb0e)

I want to know what is wrong with the configuration. Thank you.

**Comment by antz-H** [comment]
![image](https://github.com/conductor-oss/conductor/assets/43114886/86e6879b-a177-4f25-b18c-3cb57d9f8b77)

**Comment by manan164** [comment]
Hi @antz-H , Can you please try giving redis hosts as `conductor.redis.hosts=10.200.0.69:6379:us-east-1c`? The last argument is the availability zone which can be any string currently.

**Comment by antz-H** [comment]
@manan164  Thanks a lot . This issue was resolved after configuration.

But another issue appeared.

Some issue about postgresql which I don't want to use it and I don't confige it in above configuration-file.

![image](https://github.com/conductor-oss/conductor/assets/43114886/6cf5e9e3-1e26-4408-8342-5f749a376c5e)

**Comment by antz-H** [comment]
ok, when i add below configuration , every thing is ok
```
spring.datasource.url=jdbc:postgresql://10.200.0.69:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=root
```
