### ISSUE TITLE
[FEATURE] add support es6 in nashorn

### ISSUE THREAD

**Issue by romankh3** [conductor-oss/conductor#86]
We have faced an issue using default nashorn script engine, it doesn't support ecmascript 6 features while it could be turned on by replacing
 
```
ScriptEngine engine = new ScriptEngineManager().getEngineByName("nashorn");
```
With
```
NashornScriptEngineFactory factory = new NashornScriptEngineFactory();
ScriptEngine engine = factory.getScriptEngine("--language=es6");
```
our request is to make it configurable in order to allow users to provide flags or inject custom script engine. Thanks in advance!

**Comment by c4lm** [comment]
I'm not too familiar with the differences, but if there are any backward incompatibilities - we'll probably want to preserve them for the time being.
Regardless, script evaluators on tasks are configurable, [e.g.](https://github.com/conductor-oss/conductor/blob/06bc5fd4c9a57e9f532a6ad8eab39667ce92678d/core/src/main/java/com/netflix/conductor/core/execution/tasks/Inline.java#L79), so we could have another Evaluator (`nashorn-es6` or something).
And IMO eventually Nashorn will be marked as deprecated and graaljs will take its place as the default one (it has support for es6 by default).

**Comment by romankh3** [comment]
Thanks for a quick answer. Could you please provide an example of how can we change evaluator? 

And in which release you're going to change nashorn to graaljs? 

Best regards, Roman.

**Comment by c4lm** [comment]
> Thanks for a quick answer. Could you please provide an example of how can we change evaluator?
> 
> And in which release you're going to change nashorn to graaljs?
> 
> Best regards, Roman.

I've talked to other maintainers and we've decided that making a global setting instead of having a separate evaluator that users would have to configure in their definitions would be fine, we'll make it env variable-based.
When exactly Nashorn will be deprecated is not determined yet, but at some point it definitely will.

**Comment by c4lm** [comment]
When next release comes out, you will be able to get desired behaviour if you set env variable `CONDUCTOR_NASHORN_ES6_ENABLED` to `true`.

**Comment by c4lm** [comment]
> That's so good! Thanks a lot!
> 
> @c4lm, when are you going to release these changes?

Most likely this week
